"""add tags

Revision ID: defc79f48764
Revises: ddf478b3f8f8
Create Date: 2025-07-11 18:57:31.079897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'defc79f48764'
down_revision: Union[str, None] = 'ddf478b3f8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booktag',
    sa.Column('book_uid', sa.UUID(), nullable=False),
    sa.Column('tag_uid', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('book_uid', 'tag_uid')
    )
    op.create_table('tags',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('booktag')
    # ### end Alembic commands ###
