### get all books
GET http://127.0.0.1:8000/api/v1/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzenRlbGVrNkBnbWFpbC5jb20iLCJ1c2VyX3VpZCI6IjMwOWI2YTllLWU5NWQtNGZlYi04ZmM0LTM2ZTViMDVlNjIyNiIsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTc1MzcyMjM4MywianRpIjoiMDc0NjM5NGItN2E1Mi00OTRmLWE2ZjMtZjhiODI2Yjc5M2FhIiwicmVmcmVzaCI6ZmFsc2V9.5tm7Myi61vDL6GzIIO0U2UCTY_RoCmI4WdQakRSZyAg


### create a book
POST http://127.0.0.1:8000/api/v1/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoic21pdHBldGVyNzc3QGdtYWlsLmNvbSIsInVzZXJfdWlkIjoiMGFmNTBhZjctNTM5My00OTRkLTkxNzMtOTIzNGZjNzdlYjRmIiwicm9sZSI6InVzZXIifSwiZXhwIjoxNzUzNzE4ODg4LCJqdGkiOiJhYWI2ZTMzMS05NzgxLTQyOGUtYWI4MS01NTI5YmYzYmUwMTMiLCJyZWZyZXNoIjpmYWxzZX0.tbuRofBCuizjjd87PS22hDEsprqmkco9xTJtYdif__M

{
        "title": "Richard III",
        "author": "William Shakespeare",
        "publisher": "Thomas Creede",
        "published_date": "1599-01-01",
        "page_count": 120,
        "language": "English"
}

### visit a book
GET http://127.0.0.1:8000/api/v1/books/01e37e25-4712-4fa7-bb8a-c6fc9e22b871
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzenRlbGVrNUBnbWFpbC5jb20iLCJ1c2VyX3VpZCI6ImViMWI5ZjZiLTJlOWQtNGJhMy04MjU2LThkZmI3MzdmMzk4NCIsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTc1MTM4MjgyMiwianRpIjoiYmQ0YjEzMjUtOGU0NC00ZjIxLWI4YWEtMjY4NDVmMjQxYTE1IiwicmVmcmVzaCI6ZmFsc2V9.C_wJ_VeLGZ7tfrl_h3uSloAQ8QcheqRMBFbrx2sS9As

### update a book
PATCH http://127.0.0.1:8000/api/v1/books/6a15c3c0-a3b4-4564-ac18-d2c7bea98132
Content-Type: application/json

{
        "title": "Büszkeség és balítélet",
        "author": "Jane Austen",
        "publisher": "Egerton",
        "page_count": 3000,
        "language": "Magyar"
}

### delete a book
DELETE http://127.0.0.1:8000/api/v1/books/77705161-d7fd-43fc-be60-7691b444882c

### get books for user
GET http://127.0.0.1:8000/api/v1/books/user/e36cdd48-46f3-4da6-a673-42c5da4dac6f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoic21pdHBlaGp0ZXJAZ21haWwuY29tIiwidXNlcl91aWQiOiJlMzZjZGQ0OC00NmYzLTRkYTYtYTY3My00MmM1ZGE0ZGFjNmYiLCJyb2xlIjoidXNlciJ9LCJleHAiOjE3NTEyOTEzNzAsImp0aSI6IjA3ZWQ4OTQzLTZiYmItNGJhYy04YmNiLTg5ZjVhYmNlOTVjNSIsInJlZnJlc2giOmZhbHNlfQ.R8LGvh043cJB937Z_a6X2qbpqTzWD1r9e85ux0IjYLA
