
### create a user
POST http://127.0.0.1:8000/api/v1/users/signup
Content-Type: application/json

{
        "username": "telek",
        "name": "Teszt Elek",
        "email": "tesztelek6@gmail.com",
        "password": "123456"
}

#### login a user
POST http://127.0.0.1:8000/api/v1/users/login
Content-Type: application/json

{
  "email": "tesztelek6@gmail.com",
  "password": "123456"
}

### create refresh token
GET http://127.0.0.1:8000/api/v1/users/refresh_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoic21pdHBlaGp0ZXJAZ21haWwuY29tIiwidXNlcl91aWQiOiJlMzZjZGQ0OC00NmYzLTRkYTYtYTY3My00MmM1ZGE0ZGFjNmYifSwiZXhwIjoxNzUwNzEyOTc3LCJqdGkiOiI3YTdhYjk2OS02YjEzLTQzMzEtOTM4NS05YThhNjliMmVmZjUiLCJyZWZyZXNoIjpmYWxzZX0.OQl3PTo0w_Ws7Tc9zORAsfDksoBm0UhF8gtxIULQK40

### logout a user
GET http://127.0.0.1:8000/api/v1/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzenRlbGVrNUBnbWFpbC5jb20iLCJ1c2VyX3VpZCI6ImViMWI5ZjZiLTJlOWQtNGJhMy04MjU2LThkZmI3MzdmMzk4NCIsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTc1MTM4Mjc3MiwianRpIjoiNTFjYjczOTUtODU0My00NDhlLWJkZDQtMjU3MzUzM2ZiYzI1IiwicmVmcmVzaCI6ZmFsc2V9.WEpw0KnG7qRL4r6PTNSVHeWR4OIG5cukNAjU8GbU4mQ

### get me
GET http://127.0.0.1:8000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzenRlbGVrNUBnbWFpbC5jb20iLCJ1c2VyX3VpZCI6ImViMWI5ZjZiLTJlOWQtNGJhMy04MjU2LThkZmI3MzdmMzk4NCIsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTc1MTM4MjgyMiwianRpIjoiYmQ0YjEzMjUtOGU0NC00ZjIxLWI4YWEtMjY4NDVmMjQxYTE1IiwicmVmcmVzaCI6ZmFsc2V9.C_wJ_VeLGZ7tfrl_h3uSloAQ8QcheqRMBFbrx2sS9As

