### get all books
GET http://127.0.0.1:8000/api/v1/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoic21pdHBlaGp0ZXJAZ21haWwuY29tIiwidXNlcl91aWQiOiJlMzZjZGQ0OC00NmYzLTRkYTYtYTY3My00MmM1ZGE0ZGFjNmYifSwiZXhwIjoxNzUwODgwODQwLCJqdGkiOiIxZjQ0ZWNiYS1kZmUwLTQ4MDctOTJkYy0wYWNlMjMxYmFmYTkiLCJyZWZyZXNoIjp0cnVlfQ.DHcCsfNnIHWl_-dvkt9XDWIC9sffppP73frZYoCDtLE


### create a book
POST http://127.0.0.1:8000/api/v1/books
Content-Type: application/json

{
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "publisher": "T. Egerton",
        "published_date": "1813-01-28",
        "page_count": 279,
        "language": "English"
}

### visit a book
GET http://127.0.0.1:8000/api/v1/books/6a15c3c0-a3b4-4564-ac18-d2c7bea98132

### update a book
PATCH http://127.0.0.1:8000/api/v1/books/6a15c3c0-a3b4-4564-ac18-d2c7bea98132
Content-Type: application/json

{
        "title": "Büszkeség és balítélet",
        "author": "Jane Austen",
        "publisher": "Egerton",
        "page_count": 3000,
        "language": "Magyar"
}

### delete a book
DELETE http://127.0.0.1:8000/api/v1/books/77705161-d7fd-43fc-be60-7691b444882c